### ISSUE TITLE
Fixed "number" type returned on empty columns data while using the inferType feature 

### ISSUE THREAD

**Issue by Lostanee** [frictionlessdata/tableschema-java#72]
# Fixed "number" type returned on empty columns data while using the inferType feature 

Hi,
we notice a weird behavoir of tableschema while using the inferType feature with some specific data in input. In particular, we want to use the inferType to obtain a prediction of the datatypes of a csv passed as input. However, when this csv have a completly empty column (no data), the inferType function always assign to that column the type "number". This behavoir is the same even if the empty column is escaped with the double quote char (""). We just want that in the case of empty column, the predicted type is "string". Can this be fixed?

I will attach you some example of csv that have this behavoir.

Thanks in advance for your support!

---

Please preserve this line to notify @iSnow (lead of this repository)
[AW_229_000001_000002.csv](https://github.com/frictionlessdata/tableschema-java/files/9072727/AW_229_000001_000002.csv)
[AW_229_000001_000002_1Row.csv](https://github.com/frictionlessdata/tableschema-java/files/9072744/AW_229_000001_000002_1Row.csv)

**Comment by iSnow** [comment]
Thanks for raising the issue! First off, sorry for the late answer, I was busy with other stuff and couldn't catch up with Github.

Concerning your issue, I agree that defaulting to "number" is wrong here. I am not sure whether an empty column should default to "string" either, I guess it should be "any" because without a schema, you cannot tell what type this should be.

I recommend having a schema to ensure field types are locked down where possible.

**Comment by iSnow** [comment]
Thanks for raising the issue! First off, sorry for the late answer, I was busy with other stuff and couldn't catch up with Github.

Concerning your issue, I agree that defaulting to "number" is wrong here. I am not sure whether an empty column should default to "string" either, I guess it should be "any" because without a schema, you cannot tell what type this should be. @roll any input on this?

I recommend having a schema to ensure field types are locked down where possible.

**Comment by roll** [comment]
Hi, yes the unknown type is `any`

**Comment by iSnow** [comment]
@Lostanee could you share code that replicates the issue? Because I tried to replicate the issue and the derived Schema I get for both CSV files is:

	{
	  "fields" : [ {
	    "name" : "PERIOD",
	    "type" : "integer",
	    "format" : "default"
	  }, {
	    "name" : "SCENARIO",
	    "type" : "string",
	    "format" : "default"
	  }, {
	    "name" : "PRODUCT",
	    "type" : "string",
	    "format" : "default"
	  }, {
	    "name" : "REGION",
	    "type" : "string",
	    "format" : "default"
	  }, {
	    "name" : "CHANNEL",
	    "type" : "string",
	    "format" : "default"
	  }, {
	    "name" : "MEASURE",
	    "type" : "string",
	    "format" : "default"
	  }, {
	    "name" : "AMOUNT",
	    "type" : "number",
	    "format" : "default"
	  }, {
	    "name" : "USERUPD",
	    "type" : "string",
	    "format" : "default"
	  }, {
	    "name" : "DATEUPD",
	    "type" : "string",
	    "format" : "default"
	  }, {
	    "name" : "PROVENIENZA",
	    "type" : "string",
	    "format" : "default"
	  } ]
	}

 Which is still wrong, but as you can see, "USERUPD" and "DATEUPD" are inferred as String fields

**Comment by iSnow** [comment]
@Lostanee I've implemented a fix, but in the light of roll's comment, it will default empty columns to Any-fields, not String-fields. 

Thanks for raising the issue and the PR which was very helpful - even though I am not directly merging it, I took out the null checks on the NumberField class as you proposed. I also decided to avoid the whole dance with the TypeInferrer counting scores and just treat it as a special case.
